### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by dario-l** [dario-l/ses#15]
This issue is for writing some new ideas for next version:

 - stream id as char(60)
 - state of aggregate is not the same as the snapshot (!!!)
 - different metadata (stored separately - no duplication every row)
   - stream metadata
   - commit metadata
 - truncating streams
   - by id
   - before event id
   - max date
   - max count
 - statistics
 - interceptors (eg: caching)
 - performance (!?)
   - single round-trip to the database server (TVP is no-no, too sloooooow)
   - optimized and fine tuned indexes
 - deleted stream should discard all events and publish StreamDeletedEvent instead (to inform subscribers)
   - truncating should do the same, that is publish StreamTruncatedEvent
 - should have an option to make stream read-only
 - no sprocs (tests shows that is not needed)
 - projections
   - projector should not update checkpoint in datastore when event is not handled by projection
   - subscribing should be more explicit
   - replaying projections needs more love (eg: waiting for catching up)
 - tracking (metadata or dedicated columns in MsSql implementation ?)
   - eventId
   - correlationId
   - causationId

**Comment by clagoos** [comment]
Sometimes you want to modify two aggregates by two events with same commit id. For example: ModifyAgg1Event -> PM -> ModifyAgg2Event -> ProjectionForAgg2. And you want to close modal and refresh page after ProjectionForAgg2 finish modyfing row (with Agg2) in its table. So you wait in MVC Controller for projection to end its work with commitId. But there is an idex in db "IX_Streams_CommitId_Version". So if both aggregates happen to have the same version number, then we get Ses.WrongExpectedVersionException. So commit ids should be unique and its not possible to wait for projection. So there should be other id (correlation id?). Then it would be possible to have single correlation id in all events in a saga, and wait for projection to finish its work on this correlation id.
- add corelation id
  - it will be possible to wait (in MVC Controller) for correlation id instead of commit id (usefull when we want to wait for whole saga to finish)

**Comment by dario-l** [comment]
Ses is dead. Long live https://github.com/GetManta/manta
